In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
first = pd.read_csv("C:/Users/hp/OneDrive/Desktop/crypto_db/ASTA.csv")

In [4]:
first

,Unnamed: 0,Date,Open,High,Low,Close,Volume,Market Cap,Circulating Supply
0,0,2021-12-06,0.01515,0.01569,0.01462,0.01530,2358405.0,27540554.0,1.800036e+09
1,1,2021-12-05,0.01494,0.01598,0.01493,0.01516,4487644.0,27287980.0,1.799999e+09
2,2,2021-12-04,0.01620,0.01630,0.01435,0.01495,3607979.0,26913124.0,1.800209e+09
3,3,2021-12-03,0.01661,0.01709,0.01616,0.01619,3834099.0,29136579.0,1.799665e+09
4,4,2021-12-02,0.01677,0.01678,0.01646,0.01661,3559309.0,29897902.0,1.799994e+09
...,...,...,...,...,...,...,...,...,...
482,482,2020-08-11,0.19310,0.19350,0.19050,0.19060,128982.0,0.0,0.000000e+00
483,483,2020-08-10,0.19090,0.19310,0.19030,0.19310,216534.0,0.0,0.000000e+00
484,484,2020-08-09,0.19170,0.19340,0.19000,0.19090,31584.0,0.0,0.000000e+00
485,485,2020-08-08,0.19170,0.19170,0.19090,0.19170,22492.0,0.0,0.000000e+00
486,486,2020-08-07,0.19350,0.19350,0.19230,0.19260,165984.0,0.0,0.000000e+00

In [5]:
first.head()

,Unnamed: 0,Date,Open,High,Low,Close,Volume,Market Cap,Circulating Supply
0,0,2021-12-06,0.01515,0.01569,0.01462,0.01530,2358405.0,27540554.0,1.800036e+09
1,1,2021-12-05,0.01494,0.01598,0.01493,0.01516,4487644.0,27287980.0,1.799999e+09
2,2,2021-12-04,0.01620,0.01630,0.01435,0.01495,3607979.0,26913124.0,1.800209e+09
3,3,2021-12-03,0.01661,0.01709,0.01616,0.01619,3834099.0,29136579.0,1.799665e+09
4,4,2021-12-02,0.01677,0.01678,0.01646,0.01661,3559309.0,29897902.0,1.799994e+09